### ISSUE TITLE
Request - What is the difference between this and the original one. 

### ISSUE THREAD

**Issue by parvbhullar** [kontalk/tigase-server#3]
I'm planning to override default auth and message intercept classes. can you please give me some overview on that.

**Comment by daniele-athome** [comment]
@parvbhullar you should refer to the original Tigase project at https://projects.tigase.org/
This is a fork for some patches to the original server for Kontalk. To see the differences, you can watch the commit list here: https://github.com/kontalk/tigase-server/commits/master I always rebase my modifications on top of the latest release, so all my commits are on top.
