### ISSUE TITLE
Delete unused Accounts from server

### ISSUE THREAD

**Issue by webratte** [kontalk/tigase-server#4]
Maybe there is a open ore already closed issue and I haven't found it.

There is a testaccount of me (from alpha/betatesting). This Account (and also Kontalk) is deleted on my testphone because It's unused now.
This account was deleted on 27.March 2015 and it's still shown on my current phone.
Today is 18.June 2015.

**Comment by daniele-athome** [comment]
While the server does delete the account from its database, clients' roster will still have a reference to it (therefore the app shows it in your contacts list). I've opened an issue on the Android app tracker to unsubscribe from non existing users.
