### ISSUE TITLE
extend kontalk server network to diaspora pods

### ISSUE THREAD

**Issue by pravi** [kontalk/tigase-server#7]
diaspora already has a network of over 100 servers (pods) spread worldwide and run by community (http://podupti.me). diaspora has added support for xmpp chat and currently vines and prosody can work with diaspora. If we add diaspora authentication to tigasse, it will enable diaspora podmins to use tigasse as xmpp provider instead of vines or prosody and with kontalk extentions turned on it can easily act as a kontalk server. I can promise at least two more kontalk servers (I'm podmin at diasp.in and poddery.com) if tigasse supported diaspora. Even if we convinse a few more podmins to use tigasse that is worth the effort.

**Comment by daniele-athome** [comment]
Maybe I got it wrong, but as I understood it, it's not possible. Kontalk uses phone numbers to authenticate. You can't authenticate users through Diaspora because there is no phone number verified and linked to those accounts.
However you can always add Diaspora users through the standard XMPP roster.

**Comment by pravi** [comment]
Can't we have two authentication modules? One for diaspora users and another for kontalk users?

I just want to share a tigasse server for diaspora and kontalk.

**Comment by daniele-athome** [comment]
It would be under a different network (e.g. different domain name) and with different usernames, effectively resembling two distinct servers. If this is just about reusing a Kontalk server for Diaspora (using two different virtual hosts), an implementation is required for a Diaspora authentication module and some Kontalk extensions need to be tuned up to a multiple virtual hosts environment (they are not tested very well for that yet).

**Comment by pravi** [comment]
Yes, virtual hosts.

**Comment by daniele-athome** [comment]
Seems a nice feature, however it's outside of Kontalk. I can't give any high priority to this, sorry. Besides, I think it should be opened upstream (the Tigase project itself).

**Comment by pravi** [comment]
Opened a tigase issue https://projects.tigase.org/issues/3333

**Comment by daniele-athome** [comment]
Thanks @pravi. Although I wouldn't make it as a Kontalk feature because that is their project, Tigase... I don't know, let's see how they react.
